apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: myapp
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
