version: '3.8'

services:
  
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notes-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost",  "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  django:
    container_name: django
    build: 
      context: .
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    networks:
      - notes-app
    command: sh -c "python manage.py migrate && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    restart: always 
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    ports:
      - '5000:80'
    networks:
      - notes-app
    restart: always
    depends_on:
      - django

    
volumes:
  mysql-data:

networks:
  notes-app:
