apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-06-12T10:14:34Z"
  generation: 1
  labels:
    app: ngnix-deploy
  name: ngnix-deploy
  namespace: default
  resourceVersion: "32360"
  uid: a4efed9c-85ce-490a-81bf-0e4dcd63a524
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngnix-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngnix-deploy
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
