apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx-rc
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx-rc

  template:
    metadata:
      labels:
        app: nginx-rc
    spec:
      containers:
      - image: nginx:latest
        name: nginx
