apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-rs
  name: nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rs

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-rs
    spec:
      containers:
      - image: nginx:latest
        name: nginx

