apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    name: liveness-pod
spec:
  containers:
  - name: liveness-app
    image: busybox:latest
    args:
      - sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

