apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
spec:
  serviceAccountName: build-sa
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80