apiVersion: v1
kind: Pod
metadata:
  labels:
    name: myapp
  name: myapp
spec:
  containers:
    - name: myapp-container
      image:  busybox:1.35
      command: ["sh", "-c", "echo Myapp started && sleep infinity"]

  initContainers:
    - name: myapp-init-con
      image: busybox:1.35
      command: ["sh", "-c"]
      args: ["until nslookup svc-def.default.svc.cluster.local; do echo Waiting for service to be up; sleep 2; done;"]
    