apiVersion: v1
kind: Pod
metadata:
  name: pod-gpu-toleration
  labels:
    name: pod-gpu-toleration
spec:
  containers:
  - name: redis
    image: redis:latest
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"