kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: batches.devops.com
spec:
  group: devops.com
  names:
    plural: batches
    singular: batch
    kind: Batch
    shortNames:
      - bt
      - bh
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema: 
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "name of resource batch"
              duration:
                type: string
                description: "duration of resource batch"
              mode:
                type: string
                description: "mode of the resource batch"
            

