apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-06-13T07:21:13Z"
  generation: 1
  labels:
    app: nginx-def
  name: nginx-def
  namespace: default
  resourceVersion: "33538"
  uid: 41d2cb33-2d7a-478c-9b26-99e35753b6b7
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-def
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-def
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
