apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-06-16T12:27:06Z"
  generation: 1
  labels:
    app: deploy-nginx
  name: deploy-nginx
  namespace: nginx
  resourceVersion: "113335"
  uid: a984ea74-dc44-4199-811b-8e77bc863577
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deploy-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
