apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-nginx
  name: nginx-service
  namespace: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy-nginx
status:
  loadBalancer: {}
